// <auto-generated>
// This file is generated by SceneIdGenerator.
// DO NOT EDIT MANUALLY.
// </auto-generated>

using System;
using Lighthouse.Core;
using Lighthouse.Core.Scene;

namespace ProductNameSpace
{
    public sealed class CommonSceneId : CommonSceneKey
    {
        public static readonly CommonSceneId None = new CommonSceneId(1, string.Empty);
        public static readonly CommonSceneId GlobalHeader = new CommonSceneId(2, "GlobalHeader");

        public static ReadOnlySpan<CommonSceneId> All
        {
            get
            {
                return new CommonSceneId[]
                {
                    None,
                    GlobalHeader,
                };
            }
        }

        CommonSceneId(byte id, string name) : base(id, name)
        {
        }
    }
}
